#ifndef _CONSTANT_H
#define _CONSTANT_H

#define MAX_MEMORY 1048576
#define DEFAULT_READ_MEMORY 159 
#define HELP_COMMAND_NUM 13
#define MAX_STR_LENGTH 128
#define MAX_INSTRUCTION 10
#define MAX_HASH_BUCKET 20

#endif
